### ISSUE TITLE
Corrupted photo - maybe will be useful, please add to repo if so

### ISSUE THREAD

**Issue by PotyomkinSergey** [ianare/exif-samples#1]
![8](https://user-images.githubusercontent.com/18547122/35625197-2004c180-069a-11e8-8973-446f4d3e6d46.jpg)

**Comment by ianare** [comment]
Thanks for the image, can you make a merge request please? Thank you!

**Comment by jfmmm** [comment]
![image](https://user-images.githubusercontent.com/2498456/56062711-54e10f00-5d3b-11e9-83f5-b750f969b577.png)

Look fine here
